### ISSUE TITLE
Tweak UI

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#4760]
## Tasks

- [ ] Check styling
- [ ] Add CSS hook classes

## Views

- [ ] Table summaries views
- [ ] actions/resources/views/button-action.blade.php
- [ ] actions/resources/views/components/action.blade.php
- [ ] actions/resources/views/components/actions.blade.php
- [ ] actions/resources/views/components/group.blade.php
- [ ] actions/resources/views/group.blade.php
- [ ] actions/resources/views/grouped-action.blade.php
- [ ] actions/resources/views/icon-button-action.blade.php
- [ ] actions/resources/views/link-action.blade.php
- [ ] actions/resources/views/modal/actions/button-action.blade.php
- [ ] actions/resources/views/modal/index.blade.php
- [ ] actions/resources/views/select-action.blade.php
- [ ] app/resources/views/components/avatar/index.blade.php
- [ ] app/resources/views/components/avatar/tenant.blade.php
- [ ] app/resources/views/components/avatar/user.blade.php
- [ ] app/resources/views/components/brand.blade.php
- [ ] app/resources/views/components/card/heading.blade.php
- [ ] app/resources/views/components/card/index.blade.php
- [ ] app/resources/views/components/footer.blade.php
- [ ] app/resources/views/components/form/actions.blade.php
- [ ] app/resources/views/components/form/index.blade.php
- [ ] app/resources/views/components/global-search/actions/action.blade.php
- [ ] app/resources/views/components/global-search/actions/index.blade.php
- [ ] app/resources/views/components/global-search/index.blade.php
- [ ] app/resources/views/components/global-search/input.blade.php
- [ ] app/resources/views/components/global-search/no-results-message.blade.php
- [ ] app/resources/views/components/global-search/result-group.blade.php
- [ ] app/resources/views/components/global-search/result.blade.php
- [ ] app/resources/views/components/global-search/results-container.blade.php
- [ ] app/resources/views/components/header/heading.blade.php
- [ ] app/resources/views/components/header/index.blade.php
- [ ] app/resources/views/components/header/subheading.blade.php
- [ ] app/resources/views/components/layouts/app.blade.php
- [ ] app/resources/views/components/layouts/app/sidebar/group.blade.php
- [ ] app/resources/views/components/layouts/app/sidebar/index.blade.php
- [ ] app/resources/views/components/layouts/app/sidebar/item.blade.php
- [ ] app/resources/views/components/layouts/app/topbar/breadcrumbs.blade.php
- [ ] app/resources/views/components/layouts/app/topbar/database-notifications-trigger.blade.php
- [ ] app/resources/views/components/layouts/base.blade.php
- [ ] app/resources/views/components/layouts/card.blade.php
- [ ] app/resources/views/components/page.blade.php
- [ ] app/resources/views/components/resources/relation-managers/index.blade.php
- [ ] app/resources/views/components/tabs/index.blade.php
- [ ] app/resources/views/components/tabs/item.blade.php
- [ ] app/resources/views/components/tenant-menu.blade.php
- [ ] app/resources/views/components/topbar.blade.php
- [ ] app/resources/views/components/user-menu.blade.php
- [ ] app/resources/views/global-search/actions/button-action.blade.php
- [ ] app/resources/views/global-search/actions/icon-button-action.blade.php
- [ ] app/resources/views/global-search/actions/link-action.blade.php
- [ ] app/resources/views/login.blade.php
- [ ] app/resources/views/pages/dashboard.blade.php
- [ ] app/resources/views/pages/tenancy/register-tenant.blade.php
- [ ] app/resources/views/resources/pages/create-record.blade.php
- [ ] app/resources/views/resources/pages/edit-record.blade.php
- [ ] app/resources/views/resources/pages/list-records.blade.php
- [ ] app/resources/views/resources/pages/view-record.blade.php
- [ ] app/resources/views/resources/relation-manager.blade.php
- [ ] app/resources/views/widgets/account-widget.blade.php
- [ ] app/resources/views/widgets/filament-info-widget.blade.php
- [ ] forms/resources/views/component-container.blade.php
- [ ] forms/resources/views/components/actions/action.blade.php
- [ ] forms/resources/views/components/actions/icon-button-action.blade.php
- [ ] forms/resources/views/components/actions/modal/actions/button-action.blade.php
- [ ] forms/resources/views/components/actions/modal/index.blade.php
- [ ] forms/resources/views/components/builder.blade.php
- [ ] forms/resources/views/components/builder/block-picker.blade.php
- [ ] forms/resources/views/components/builder/block.blade.php
- [ ] forms/resources/views/components/card.blade.php
- [ ] forms/resources/views/components/checkbox-list.blade.php
- [ ] forms/resources/views/components/checkbox.blade.php
- [ ] forms/resources/views/components/color-picker.blade.php
- [ ] forms/resources/views/components/date-time-picker.blade.php
- [ ] forms/resources/views/components/field-wrapper/error-message.blade.php
- [ ] forms/resources/views/components/field-wrapper/helper-text.blade.php
- [ ] forms/resources/views/components/field-wrapper/hint.blade.php
- [ ] forms/resources/views/components/field-wrapper/index.blade.php
- [ ] forms/resources/views/components/field-wrapper/inline.blade.php
- [ ] forms/resources/views/components/field-wrapper/label.blade.php
- [ ] forms/resources/views/components/fieldset.blade.php
- [ ] forms/resources/views/components/file-upload.blade.php
- [ ] forms/resources/views/components/grid.blade.php
- [ ] forms/resources/views/components/group.blade.php
- [ ] forms/resources/views/components/hidden.blade.php
- [ ] forms/resources/views/components/key-value.blade.php
- [ ] forms/resources/views/components/markdown-editor.blade.php
- [ ] forms/resources/views/components/markdown-editor/toolbar-button.blade.php
- [ ] forms/resources/views/components/multiple-file-upload.blade.php
- [ ] forms/resources/views/components/placeholder.blade.php
- [ ] forms/resources/views/components/radio.blade.php
- [ ] forms/resources/views/components/repeater.blade.php
- [ ] forms/resources/views/components/rich-editor.blade.php
- [ ] forms/resources/views/components/rich-editor/toolbar-button.blade.php
- [ ] forms/resources/views/components/section.blade.php
- [ ] forms/resources/views/components/select.blade.php
- [ ] forms/resources/views/components/tabs.blade.php
- [ ] forms/resources/views/components/tabs/tab.blade.php
- [ ] forms/resources/views/components/tags-input.blade.php
- [ ] forms/resources/views/components/text-input.blade.php
- [ ] forms/resources/views/components/textarea.blade.php
- [ ] forms/resources/views/components/toggle.blade.php
- [ ] forms/resources/views/components/wizard.blade.php
- [ ] forms/resources/views/components/wizard/step.blade.php
- [ ] forms/stubs/scaffolding/resources/views/layouts/app.blade.php
- [ ] notifications/resources/views/actions/button-action.blade.php
- [ ] notifications/resources/views/actions/group.blade.php
- [ ] notifications/resources/views/actions/grouped-action.blade.php
- [ ] notifications/resources/views/actions/link-action.blade.php
- [ ] notifications/resources/views/components/actions/action.blade.php
- [ ] notifications/resources/views/components/actions/index.blade.php
- [ ] notifications/resources/views/components/body.blade.php
- [ ] notifications/resources/views/components/close-button.blade.php
- [ ] notifications/resources/views/components/database/index.blade.php
- [ ] notifications/resources/views/components/database/modal/actions.blade.php
- [ ] notifications/resources/views/components/database/modal/empty-state.blade.php
- [ ] notifications/resources/views/components/database/modal/heading.blade.php
- [ ] notifications/resources/views/components/database/modal/index.blade.php
- [ ] notifications/resources/views/components/database/trigger.blade.php
- [ ] notifications/resources/views/components/date.blade.php
- [ ] notifications/resources/views/components/echo.blade.php
- [ ] notifications/resources/views/components/icon.blade.php
- [ ] notifications/resources/views/components/notification.blade.php
- [ ] notifications/resources/views/components/title.blade.php
- [ ] notifications/resources/views/notification.blade.php
- [ ] notifications/resources/views/notifications.blade.php
- [ ] notifications/stubs/scaffolding/resources/views/layouts/app.blade.php
- [ ] spatie-laravel-settings-plugin/resources/views/pages/settings-page.blade.php
- [ ] support/resources/views/assets.blade.php
- [ ] support/resources/views/components/button.blade.php
- [ ] support/resources/views/components/dropdown/header.blade.php
- [ ] support/resources/views/components/dropdown/index.blade.php
- [ ] support/resources/views/components/dropdown/list/index.blade.php
- [ ] support/resources/views/components/dropdown/list/item.blade.php
- [ ] support/resources/views/components/dropdown/list/separator.blade.php
- [ ] support/resources/views/components/grid/column.blade.php
- [ ] support/resources/views/components/grid/index.blade.php
- [ ] support/resources/views/components/hr.blade.php
- [ ] support/resources/views/components/icon-button.blade.php
- [ ] support/resources/views/components/icon.blade.php
- [ ] support/resources/views/components/input/affixes.blade.php
- [ ] support/resources/views/components/input/index.blade.php
- [ ] support/resources/views/components/input/select.blade.php
- [ ] support/resources/views/components/link.blade.php
- [ ] support/resources/views/components/loading-indicator.blade.php
- [ ] support/resources/views/components/modal/actions.blade.php
- [ ] support/resources/views/components/modal/heading.blade.php
- [ ] support/resources/views/components/modal/index.blade.php
- [ ] support/resources/views/components/modal/subheading.blade.php
- [ ] tables/resources/views/actions/bulk-action.blade.php
- [ ] tables/resources/views/actions/button-action.blade.php
- [ ] tables/resources/views/actions/group.blade.php
- [ ] tables/resources/views/actions/grouped-action.blade.php
- [ ] tables/resources/views/actions/icon-button-action.blade.php
- [ ] tables/resources/views/actions/link-action.blade.php
- [ ] tables/resources/views/actions/modal/actions/button-action.blade.php
- [ ] tables/resources/views/columns/badge-column.blade.php
- [ ] tables/resources/views/columns/checkbox-column.blade.php
- [ ] tables/resources/views/columns/color-column.blade.php
- [ ] tables/resources/views/columns/icon-column.blade.php
- [ ] tables/resources/views/columns/image-column.blade.php
- [ ] tables/resources/views/columns/layout/grid.blade.php
- [ ] tables/resources/views/columns/layout/panel.blade.php
- [ ] tables/resources/views/columns/layout/split.blade.php
- [ ] tables/resources/views/columns/layout/stack.blade.php
- [ ] tables/resources/views/columns/select-column.blade.php
- [ ] tables/resources/views/columns/tags-column.blade.php
- [ ] tables/resources/views/columns/text-column.blade.php
- [ ] tables/resources/views/columns/text-input-column.blade.php
- [ ] tables/resources/views/columns/toggle-column.blade.php
- [ ] tables/resources/views/components/actions/action.blade.php
- [ ] tables/resources/views/components/actions/cell.blade.php
- [ ] tables/resources/views/components/actions/index.blade.php
- [ ] tables/resources/views/components/bulk-actions/index.blade.php
- [ ] tables/resources/views/components/bulk-actions/trigger.blade.php
- [ ] tables/resources/views/components/cell.blade.php
- [ ] tables/resources/views/components/checkbox/cell.blade.php
- [ ] tables/resources/views/components/checkbox/index.blade.php
- [ ] tables/resources/views/components/columns/column.blade.php
- [ ] tables/resources/views/components/columns/layout.blade.php
- [ ] tables/resources/views/components/container.blade.php
- [ ] tables/resources/views/components/empty-state/description.blade.php
- [ ] tables/resources/views/components/empty-state/heading.blade.php
- [ ] tables/resources/views/components/empty-state/index.blade.php
- [ ] tables/resources/views/components/filters/dropdown.blade.php
- [ ] tables/resources/views/components/filters/index.blade.php
- [ ] tables/resources/views/components/filters/indicators.blade.php
- [ ] tables/resources/views/components/filters/trigger.blade.php
- [ ] tables/resources/views/components/header-cell.blade.php
- [ ] tables/resources/views/components/header/description.blade.php
- [ ] tables/resources/views/components/header/heading.blade.php
- [ ] tables/resources/views/components/header/index.blade.php
- [ ] tables/resources/views/components/loading-cell.blade.php
- [ ] tables/resources/views/components/pagination/index.blade.php
- [ ] tables/resources/views/components/pagination/item.blade.php
- [ ] tables/resources/views/components/pagination/records-per-page-selector.blade.php
- [ ] tables/resources/views/components/reorder/cell.blade.php
- [ ] tables/resources/views/components/reorder/handle.blade.php
- [ ] tables/resources/views/components/reorder/indicator.blade.php
- [ ] tables/resources/views/components/reorder/trigger.blade.php
- [ ] tables/resources/views/components/row.blade.php
- [ ] tables/resources/views/components/search-input.blade.php
- [ ] tables/resources/views/components/selection-indicator.blade.php
- [ ] tables/resources/views/components/table.blade.php
- [ ] tables/resources/views/components/toggleable/index.blade.php
- [ ] tables/resources/views/components/toggleable/trigger.blade.php
- [ ] tables/resources/views/index.blade.php
- [ ] tables/stubs/scaffolding/resources/views/layouts/app.blade.php
- [ ] widgets/resources/views/chart-widget.blade.php
- [ ] widgets/resources/views/components/card/heading.blade.php
- [ ] widgets/resources/views/components/card/index.blade.php
- [ ] widgets/resources/views/components/stats/card.blade.php
- [ ] widgets/resources/views/components/stats/index.blade.php
- [ ] widgets/resources/views/components/widget.blade.php
- [ ] widgets/resources/views/components/widgets.blade.php
- [ ] widgets/resources/views/stats-overview-widget.blade.php
- [ ] widgets/resources/views/stats-overview-widget/card.blade.php
- [ ] widgets/resources/views/table-widget.blade.php

**Comment by awcodes** [comment]
And what exactly are we doing with all these? Lol.

**Comment by zepfietje** [comment]
Want to make sure all these views match design updates (and get rid of current inconsistencies).

**Comment by zepfietje** [comment]
Going to approach this differently.
Also added a separate roadmap entry for "Add more CSS hook classes and document them".
